--!strict

local CollectionService = game:GetService("CollectionService");

local React = require(script.Parent.Parent.Parent.roblox_packages.react)

local function useRefreshDialogueMakerScripts()

  return React.useCallback(function()
  
    local conversationScripts = CollectionService:GetTagged("DialogueMakerConversationScript");
    local dialogueScripts = CollectionService:GetTagged("DialogueMakerDialogueScript");
    local loaderScripts = CollectionService:GetTagged("DialogueMakerLoader");

    for _, autoGeneratedScripts in {conversationScripts, dialogueScripts, loaderScripts} do
      
      for _, autoGeneratedScript in autoGeneratedScripts do

        task.spawn(function()
        
          -- Determine the correct template and target script based on the type.
          local templateScript = (
            if autoGeneratedScript:HasTag("DialogueMakerConversationScript") then script.Parent.Parent.Templates.ConversationTemplate
            elseif autoGeneratedScript:HasTag("DialogueMakerDialogueScript") then script.Parent.Parent.Templates.DialogueTemplate
            elseif autoGeneratedScript:HasTag("DialogueMakerLoader") then script.Parent.Parent.Templates.LoaderTemplate
            else nil
          );
          
          if not templateScript then

            warn(`No template found for script: {autoGeneratedScript:GetFullName()}.`);
            return;
          
          end;

          -- Reset the script contents to the template.
          autoGeneratedScript.Source = templateScript.Source;

          -- Replace packages.
          local dialogueMakerPluginSettings = CollectionService:GetTagged("DialogueMakerPluginSettings")[1];
          assert(dialogueMakerPluginSettings, "DialogueMakerPluginSettings not found.");

          local packagesFolder = dialogueMakerPluginSettings:FindFirstChild("packages");
          assert(packagesFolder, "packages folder not found in DialogueMakerPluginSettings.");

          local locationSettingInstance = packagesFolder:FindFirstChild("location");
          assert(locationSettingInstance and locationSettingInstance:IsA("ObjectValue"), "location setting instance not found in packages folder.");

          autoGeneratedScript.Source = autoGeneratedScript.Source:gsub("local packages = *\n", `local packages = {locationSettingInstance.Value:GetFullName()};\n`);

          -- Replace the properties string in the script.
          local settingsFolder = autoGeneratedScript:FindFirstChild("Settings");
          if not settingsFolder then

            return;

          end;

          local settingsString = "settings = {";
          local extraSpaces = if autoGeneratedScripts == loaderScripts then "      " else "";

          for _, categoryFolder in settingsFolder:GetChildren() do

            if settingsFolder:IsA("Folder") then

              settingsString = `{settingsString}\n    {extraSpaces}{categoryFolder.Name} = \{`;

              for _, settingInstance in categoryFolder:GetChildren() do

                if settingInstance:IsA("ValueBase") then

                  settingsString = `\n      {extraSpaces}{settingInstance.Name} = script.Settings.{categoryFolder.Name}.{settingInstance.Name}.Value;`;

                end;

              end;

              settingsString = `\n    {extraSpaces}{settingsString}};`;

            end;

          end;

          settingsString = `\n  {extraSpaces}};\n`;

          autoGeneratedScript.Source = autoGeneratedScript.Source:gsub("-- START REPLACEMENT*-- END REPLACEMENT\n", settingsString);

        end);

      end;
      
    end;

  end, {});

end;

return useRefreshDialogueMakerScripts;