--!strict

local CollectionService = game:GetService("CollectionService");

local root = script.Parent.Parent.Parent;
local React = require(root.roblox_packages.react)

local function useRefreshDialogueMakerScripts()

  return React.useCallback(function()
  
    local conversationScripts = CollectionService:GetTagged("DialogueMakerConversationScript");
    local dialogueScripts = CollectionService:GetTagged("DialogueMakerDialogueScript");
    local loaderScripts = CollectionService:GetTagged("DialogueMakerLoader");
    local dialogueMakerKits = CollectionService:GetTagged("DialogueMakerKit");
    local dialogueMakerKit;
    for _, kit in dialogueMakerKits do
      
      if not kit:IsDescendantOf(root) then
        
        dialogueMakerKit = kit;
        break;
        
      end;
      
    end;

    local dialogueMakerPackageContainers = CollectionService:GetTagged("DialogueMakerPackages");
    local dialogueMakerPackages: Instance? = if dialogueMakerKit then dialogueMakerKit:FindFirstChild("Packages") else nil;

    if not dialogueMakerPackages then

      for _, packageContainer in dialogueMakerPackageContainers do
        
        if not packageContainer:IsDescendantOf(root) then
          
          dialogueMakerPackages = packageContainer;
          break;
          
        end;
        
      end;

    end;

    assert(dialogueMakerPackages, `Dialogue Maker packages not found. Make sure you have the Dialogue Maker packages in your game, and tag the folder with "DialogueMakerPackages".`);

    for _, autoGeneratedScripts in {conversationScripts, dialogueScripts, loaderScripts} do
      
      for _, autoGeneratedScript in autoGeneratedScripts do
        
        if autoGeneratedScript:IsDescendantOf(root) then

          continue;

        end;

        task.spawn(function()
        
          -- Determine the correct template and target script based on the type.
          local templateScript = (
            if autoGeneratedScript:HasTag("DialogueMakerConversationScript") then root.Templates.ConversationTemplate
            elseif autoGeneratedScript:HasTag("DialogueMakerDialogueScript") then root.Templates.DialogueTemplate
            elseif autoGeneratedScript:HasTag("DialogueMakerLoader") then root.Templates.LoaderTemplate
            else nil
          );
          
          if not templateScript then

            warn(`No template found for script: {autoGeneratedScript:GetFullName()}.`);
            return;
          
          end;

          -- Reset the script contents to the template.
          autoGeneratedScript.Source = templateScript.Source;

          -- Replace packages.
          autoGeneratedScript.Source = autoGeneratedScript.Source:gsub("local packages = [^\n]*", `local packages = game.{dialogueMakerPackages:GetFullName()};\n`);

          -- Replace the properties string in the script.
          -- First, edit the settings.
          local settingsFolder = autoGeneratedScript:FindFirstChild("Settings");
          if not settingsFolder then

            return;

          end;

          local settingsString = "settings = {";
          local extraSpaces = if autoGeneratedScripts == loaderScripts then "      " else "";

          for _, categoryFolder in settingsFolder:GetChildren() do

            if settingsFolder:IsA("Folder") then

              settingsString = `{settingsString}\n    {extraSpaces}{categoryFolder.Name} = \{`;

              for _, settingInstance in categoryFolder:GetChildren() do

                if settingInstance:IsA("ValueBase") then

                  settingsString = `{settingsString}\n      {extraSpaces}{settingInstance.Name} = script.Settings.{categoryFolder.Name}.{settingInstance.Name}.Value;`;

                end;

              end;

              settingsString = `{settingsString}\n    {extraSpaces}};`;

            end;

          end;

          settingsString = `{settingsString}\n  {extraSpaces}};`;

          autoGeneratedScript.Source = autoGeneratedScript.Source:gsub("-- START REPLACEMENT.*-- END REPLACEMENT[^\n]*", settingsString);

        end);

      end;
      
    end;

  end, {});

end;

return useRefreshDialogueMakerScripts;